<a href="https://colab.research.google.com/github/DEBANKASALUI/Artifical-Neural-Network-Deep-Learning/blob/main/KERAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KERAS ASSIGNMENT

In [ ]:
import tensorflow as tf

# Define constants
x = tf.constant([1, 2, 3], dtype=tf.float32)
w = tf.constant(2.0, dtype=tf.float32)
b = tf.constant(1.0, dtype=tf.float32)

# Compute y = wx + b
y = w * x + b
print("Predicted output (y):", y.numpy())

# Create two tensors
tensor1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Addition
add_result = tf.add(tensor1, tensor2)
print("Addition result:\n", add_result.numpy())

# Multiplication
mul_result = tf.multiply(tensor1, tensor2)
print("Multiplication result:\n", mul_result.numpy())

# Reshaping
reshape_result = tf.reshape(tensor1, [4, 1])
print("Reshaped tensor:\n", reshape_result.numpy())


Predicted output (y): [3. 5. 7.]
Addition result:
 [[ 6.  8.]
 [10. 12.]]
Multiplication result:
 [[ 5. 12.]
 [21. 32.]]
Reshaped tensor:
 [[1.]
 [2.]
 [3.]
 [4.]]


In [ ]:
import tensorflow as tf

# 1. Create tensors
scalar = tf.constant(10)
vector = tf.constant([1, 2, 3, 4, 5])
matrix = tf.constant([[1, 2], [3, 4]])

print("Scalar:", scalar.numpy(), "Shape:", scalar.shape)
print("Vector:", vector.numpy(), "Shape:", vector.shape)
print("Matrix:\n", matrix.numpy(), "Shape:", matrix.shape)

# 2. Tensor Operations
tensor_a = tf.constant([1, 2, 3])
tensor_b = tf.constant([4, 5, 6])

add_result = tf.add(tensor_a, tensor_b)
sub_result = tf.subtract(tensor_a, tensor_b)
mul_result = tf.multiply(tensor_a, tensor_b)

print("\nAddition:", add_result.numpy())
print("Subtraction:", sub_result.numpy())
print("Multiplication:", mul_result.numpy())

# 3. Reshape and Type Conversion
tensor_c = tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.int32)
reshaped = tf.reshape(tensor_c, [2, 3])
converted = tf.cast(tensor_c, dtype=tf.float32)

print("\nReshaped (2x3):\n", reshaped.numpy())
print("Converted to float:", converted.numpy())

# 4. Statistical Operations
tensor_d = tf.constant([10, 20, 30, 40, 50], dtype=tf.float32)

sum_val = tf.reduce_sum(tensor_d)
mean_val = tf.reduce_mean(tensor_d)
max_val = tf.reduce_max(tensor_d)
min_val = tf.reduce_min(tensor_d)

print("\nSum:", sum_val.numpy())
print("Mean:", mean_val.numpy())
print("Max:", max_val.numpy())
print("Min:", min_val.numpy())


Scalar: 10 Shape: ()
Vector: [1 2 3 4 5] Shape: (5,)
Matrix:
 [[1 2]
 [3 4]] Shape: (2, 2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]

Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]
Converted to float: [1. 2. 3. 4. 5. 6.]

Sum: 150.0
Mean: 30.0
Max: 50.0
Min: 10.0


31. Build a Simple Sequential Model
Input: X=[[1],[2],[3],[4]], y=[2,4,6,8]
Task: Create Sequential model with one Dense layer.
Output: Model summary with layers and parameters.

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Input and output data
X = [[1],[2],[3],[4]]
y = [2,4,6,8]

# Build Sequential model with one Dense layer
model = keras.Sequential([
    layers.Dense(1, input_shape=(1,))
])

# Show model summary
model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

32. Add Dense Layers and Activation Functions
Input: Same as above
Task: Add hidden layer (ReLU) and output layer.
Output: Model summary showing activations.

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Input and output data
X = [[1],[2],[3],[4]]
y = [2,4,6,8]

# Build Sequential model with hidden (ReLU) and output layer
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),  # hidden layer
    layers.Dense(1)  # output layer
])

# Show model summary
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 8)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 25 (100.00 B)

 Trainable params: 25 (100.00 B)

 Non-trainable params: 0 (0.00 B)

33. Compile Model
Input: Same
Task: Compile with optimizer=adam, loss=mse.
Output: Model compiles successfully.

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Input and output data
X = [[1],[2],[3],[4]]
y = [2,4,6,8]

# Build Sequential model with hidden (ReLU) and output layer
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),  # hidden layer
    layers.Dense(1)  # output layer
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

print("Model compiled successfully!")


Model compiled successfully!


34. Train Model
Input: Same
Task: Train using fit() for multiple epochs.
Output: Loss decreases over epochs.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Input and output data as NumPy arrays
X = np.array([[1],[2],[3],[4]], dtype=float)
y = np.array([2,4,6,8], dtype=float)

# Build Sequential model with hidden (ReLU) and output layer
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),  # hidden layer
    layers.Dense(1)  # output layer
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Train the model for multiple epochs
history = model.fit(X, y, epochs=50, verbose=0)

# Print first 10 loss values to show decrease
print("First 10 losses:", history.history['loss'][:10])
print("Final loss:", history.history['loss'][-1])


First 10 losses: [17.59510040283203, 17.50083351135254, 17.406768798828125, 17.312902450561523, 17.21924591064453, 17.125797271728516, 17.032562255859375, 16.939542770385742, 16.846744537353516, 16.754165649414062]
Final loss: 13.24390983581543


35. Evaluate Model
Input: X_test=[[5],[6]], y_test=[10,12]
Task: Evaluate model.
Output: Loss value printed.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Training data
X = np.array([[1],[2],[3],[4]], dtype=float)
y = np.array([2,4,6,8], dtype=float)

# Build model
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),  # hidden layer
    layers.Dense(1)  # output layer
])

# Compile
model.compile(optimizer='adam', loss='mse')

# Train
model.fit(X, y, epochs=50, verbose=0)

# Test data
X_test = np.array([[5],[6]], dtype=float)
y_test = np.array([10,12], dtype=float)

# Evaluate
loss = model.evaluate(X_test, y_test, verbose=0)
print("Loss on test data:", loss)


Loss on test data: 119.64669799804688


36. Predict Output
Input: [[7]]
Task: Predict using model.
Output: Approx output [[14]].

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Training data
X = np.array([[1],[2],[3],[4]], dtype=float)
y = np.array([2,4,6,8], dtype=float)

# Build model
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),  # hidden layer
    layers.Dense(1)  # output layer
])

# Compile
model.compile(optimizer='adam', loss='mse')

# Train
model.fit(X, y, epochs=50, verbose=0)

# Predict for input [[7]]
prediction = model.predict(np.array([[7]], dtype=float))
print("Prediction for 7:", prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Prediction for 7: [[-0.95434326]]


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Training data
X = np.array([[1],[2],[3],[4]], dtype=float)
y = np.array([2,4,6,8], dtype=float)

# Build model
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),  # hidden layer
    layers.Dense(1)  # output layer
])

# Compile
model.compile(optimizer='adam', loss='mse')

# Train
model.fit(X, y, epochs=50, verbose=0)

# Predict for input [[7]]
prediction = model.predict(np.array([[7]], dtype=float))
print("Prediction for 7:", prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
Prediction for 7: [[1.9495523]]


37. Binary Classification
Input: X=[[0],[1],[2],[3]], y=[0,0,1,1]
Task: Use sigmoid and binary_crossentropy.
Output: Predictions close to [0,0,1,1].

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Input data
X = np.array([[0],[1],[2],[3]], dtype=float)
y = np.array([0,0,1,1], dtype=float)

# Build binary classification model
model = keras.Sequential([
    layers.Dense(4, activation='relu', input_shape=(1,)),  # hidden layer
    layers.Dense(1, activation='sigmoid')  # output layer for binary classification
])

# Compile with binary crossentropy
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train
model.fit(X, y, epochs=100, verbose=0)

# Predictions
predictions = model.predict(X)
print("Predictions:", predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
Predictions: [[0.5]
 [0.5]
 [0.5]
 [0.5]]


38. Multi-Class Classification
Input: X=[[1],[2],[3]], y=[0,1,2]
Task: Use softmax and sparse categorical crossentropy.
Output: Probability distribution.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Input data
X = np.array([[1],[2],[3]], dtype=float)
y = np.array([0,1,2], dtype=int)  # class labels

# Build multi-class classification model
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),  # hidden layer
    layers.Dense(3, activation='softmax')  # output layer for 3 classes
])

# Compile with sparse categorical crossentropy
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train
model.fit(X, y, epochs=100, verbose=0)

# Predictions
predictions = model.predict(X)
print("Predictions (probability distributions):")
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
Predictions (probability distributions):
[[0.3650528  0.30793667 0.32701045]
 [0.43141037 0.20699921 0.3615904 ]
 [0.48610583 0.13267261 0.3812216 ]]


39. EarlyStopping
Input: Any dataset
Task: Use EarlyStopping callback.
Output: Training stops early.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

# Example dataset
X = np.array([[1],[2],[3],[4]], dtype=float)
y = np.array([2,4,6,8], dtype=float)

# Build model
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),
    layers.Dense(1)
])

# Compile
model.compile(optimizer='adam', loss='mse')

# Define EarlyStopping callback
early_stop = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)

# Train with EarlyStopping
history = model.fit(X, y, epochs=200, callbacks=[early_stop], verbose=0)

print("Training stopped after", len(history.history['loss']), "epochs")
print("Final loss:", history.history['loss'][-1])


Training stopped after 200 epochs
Final loss: 3.5639429092407227


40. Save and Load Model
Input: Trained model
Task: Save and reload model.
Output: Same predictions after loading.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Training data
X = np.array([[1],[2],[3],[4]], dtype=float)
y = np.array([2,4,6,8], dtype=float)

# Build model
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),
    layers.Dense(1)
])

# Compile
model.compile(optimizer='adam', loss='mse')

# Train
model.fit(X, y, epochs=50, verbose=0)

# Save using the new Keras format
model.save("my_model.keras")

# Load the model back
loaded_model = keras.models.load_model("my_model.keras")

# Verify predictions
print("Original model prediction:", model.predict(np.array([[7]], dtype=float)))
print("Loaded model prediction:", loaded_model.predict(np.array([[7]], dtype=float)))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
Original model prediction: [[1.9726378]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
Loaded model prediction: [[1.9726378]]
